language: node_js
node_js: 9
deploy:
  provider: npm
  email: mugen.xyz@gmail.com
  api_key:
    secure: eSju30NanjynyNp9xnCu7XJwP6y5h7D8+zJ2Zb3Au092YTyeGPHZaTXYA8UGnFaCaEhd8yC38ls0viVSDRFZc9KDtanAeSIHCjNmDV2Pl4SEmV/0F71rwyI1KtLC4AUredpzo85dEcgRqr/lgkla/xaq6CRSvieDx5fcePVwp1VUVG72ruLn/M5m//UtIDHE/fng0c5MUtCCJoQP02kK0k0pDuDe7S4qEzHoLtc9W0S3EdJtJ04AeJ9lKhjZN4BGbTpM0frn5cnxnV+8i+iKxcV7VfZ/732EVg0IwgGrSbt7gmdPYTKywI3dwX4h0GbLx3m+EOY1X6iKdgcXuL+8BIvcQfTV9EWoHHJMWRmusvi50maIck4qdKsjLOeDngGZyZnumJC05XgyYQc2f1LbuV8sBOhkE0O1U2+mhr/5pmRww1M+O0i1WuQmf7KPAyapNRrzStldJsM/rvotElgz4hjLLx070S9+gCtc0Mg8AmgqbtQ99ISv+vrx4InQdwBlDZpf/NxddTu0+pzJJvAd48oPGtyrX/yk76IR3UF7Gc04xUhgh677XGDYQhb0nMNE+x/SsA3RJ0eJtwf72xKJO/A7pdJXGvz6KO9EPiCmFzgsRya//VB8e6t1WWFrAycMJ8fSobD+CROvIPzRGEkF50UFmJiD4IvO8B6mEmuZ4qg=
  on:
    tags: true
    repo: sunya9/layout.css
notifications:
  slack:
    secure: mVJYQ0sS/SIYDG1E57d8/ci7jaqjNKMcCt4gtR+/fjGWBNMN3Ln/nYLykMW/eN6qSWhjdPTR4dtK7l/mp0ewv6AmQ26upT9vAAX5gRIiO+5XAZukx3MOVdyb0G4YRsOskcHMkyAJbf0f2NNQTbu5LiCFH5wwCX4N3ggq1aZU+5rJcrwt526hXE4GRUbc8+4u/F0SvMQ83tdyQxdpwtwvhzLTdCnjmBmHq0BG/a2LYWrHxgl8Irv8RGCKxRyaQwSN3kEHGpULIM4YMyTG8We5hQMZ22Dja018frFDOlpcKzbQrxpnO9vgcPfoadJENUTaMAey6QUAtHXU8voeDBZG9sn+EvHI3Sax5Qwsock/QK5SUvIxEFeto/68xoMoQ72+R9BRgGtfAz6QHR4E3lJVOVaYnwJBtK+3IvHyhZ1o9Dw0bJfagVujQ5pWs3t2A+KnII2IMEsp7ivskhZgJXJoGc+MDCiqRfRP10qd7jqWD3toBD/qssda18szcuPkgLD6S6krfNqq7oPF7HBFL6o60Bw6atneenuqCyzHpwVFSzZ0INfoMyM3lvwjNPbE7JFQx2APEgudNcN4NeHXfbW3TJl3b6Ih9ZCSnTj2mxOkh6RptCnnGpBfBRkl3j9YbxFQmxHiMrkrvtwZDvg0Xp5esRTnvwAe3Lzvph3oxQ2qwU4=
  email: false

